### ISSUE TITLE
OutOfMemoryError : Java Heap Space while reading a spss (.sav) file

### ISSUE THREAD

**Issue by everything73** [bedatadriven/spss-reader#4]
The error I encountered is :

> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> 	at com.bedatadriven.spss.SpssDataFileReader.<init>(SpssDataFileReader.java:102)
> 	at com.bedatadriven.spss.SpssDataFileReader.<init>(SpssDataFileReader.java:78)
> 	at Demo.main(Demo.java:38)

I had a SPSS file. I copied the first half of its contents to another file and saved it as another SPSS (.sav) file. On reading that file, it threw the above error. It passed the "$FL2" check . Is there a way to avoid the OutOfMemoryError?

The file I used is zipped and attached below:
[y.sav.zip](https://github.com/bedatadriven/spss-reader/files/3037356/y.sav.zip)
 
Thanks

**Comment by everything73** [comment]
It throws the OutOfMemoryError at this point as this.fileHeader.getCaseSize() returns some big value .
> this.variableRecords = new SpssVariable[this.fileHeader.getCaseSize()];

**Comment by akbertram** [comment]
There's most likely a problem reading the header then.

Maybe step through this code here:
https://github.com/bedatadriven/spss-reader/blob/master/src/main/java/com/bedatadriven/spss/FileHeader.java#L32

Do the rest of the values look correct?

**Comment by everything73** [comment]
I went through the code. 
https://github.com/bedatadriven/spss-reader/blob/master/src/main/java/com/bedatadriven/spss/FileHeader.java#L32
 
This is where it reads the values incorrectly and leads to OutOfMemoryError, when trying to initialize SPSSVariable array with that big value. 
Correct the code and update it

**Comment by akbertram** [comment]
Great! If you open a pull request I'm happy to merge it asap

**Comment by everything73** [comment]
Sorry, I don't know much about github . Never used it before

**Comment by akbertram** [comment]
Send the patch by email if that's easier!

**Comment by everything73** [comment]
I don't have the patch now and I am not sure if it has anymore problems.
All I know, that's the only place(this.variableRecords) where it can lead to OutOfMemory Error. Rest you gotta catch the exception if any occurs.

**Comment by everything73** [comment]
Are you going to fix it in near future? As you see, it can prove out to be a big problem .

**Comment by akbertram** [comment]
Unfortunately I won't have time to look at it in the next two months, but I'm happy to merge a fix if you can fix it!

**Comment by everything73** [comment]
Ok . Will open a pull request if I find a fix for it.

**Comment by akbertram** [comment]
I've taken a look at the attached test file (y.sav). The file header seems to be corrupted:
* The 4 bytes following the product name should contain the layout code, equal to value of 2 or 3. The file contains the bytes 0x01 0x03 0x59 0x40, which don't make sense in either little- or big-endian encoding. 
* The next 4 bytes should be the case size, which has a value that doesn't make sense in either little- or big-endian format.

I've also tried to open the file with [pspp](https://www.gnu.org/software/pspp/) and it also reports that the file is invalid.
