### ISSUE TITLE
Newest Version on MvnCentral?

### ISSUE THREAD

**Issue by cgivre** [bedatadriven/spss-reader#6]
Thank you for writing this library!  I'm interested in including it in an Apache Top Level Project and I'm wondering whether you can submit the latest version to Maven Central?
Thanks!

**Comment by akbertram** [comment]
Hi! Yes, sorry, that's been on my todo list for awhile. It's been awhile since the last release so it will take some time to fight with GnuGPG/Maven/Sonatype. I'll try to do it the next week!

**Comment by cgivre** [comment]
@akbertram 
Thanks!  I'm looking to build a format plugin for Apache Drill which will enable you to read, query and analyze SPSS files using SQL.  
Your library looks like it will be very easy to integrate with Drill so I'm pretty excited about that.

**Comment by cgivre** [comment]
Here's the PR if you want to take a look:
https://github.com/apache/drill/pull/2067

Once committed, you'll be able to query and analyze SPSS files as if they were a database table using Drill.

**Comment by akbertram** [comment]
Version 1.3 is now released to Maven central:
https://repo1.maven.org/maven2/com/bedatadriven/spss/spss-reader/1.3/

It make take a few more for other indexes to update.
