### ISSUE TITLE
[QUESTION]: Reading Date/Time Type

### ISSUE THREAD

**Issue by cgivre** [bedatadriven/spss-reader#7]
I was wondering whether it is possible to determine whether a given field contains a date, time or datetime value with the SPSS reader?
Thanks!

**Comment by akbertram** [comment]
I think you need to look at the variable's print or write format:
https://github.com/bedatadriven/spss-reader/blob/4dbd4c60eb13c4ef91370742f7b3041eca5f612d/src/main/java/com/bedatadriven/spss/SpssVariableFormat.java#L11

/cc @Elmervc
